core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslbackend=openssl
http.sslcainfo=D:/Arquivos de Programa/Git/mingw64/ssl/certs/ca-bundle.crt
credential.helper=manager
user.name=dclimaites
user.email=diegoclimaites@outlook.com
filesystem.Oracle Corporation|1.8.0_221|-803535054.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|1.8.0_221|-803535054.minracythreshold=0 nanoseconds
filesystem.Oracle Corporation|1.8.0_221|-1502878794.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|1.8.0_221|-1502878794.minracythreshold=0 nanoseconds
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/dclimaites/TrabalhoWebServices.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.issue-3.remote=origin
branch.issue-3.merge=refs/heads/issue-3
